import { Professor, TipoAula, Aula, Aluno, Treino } from "@/types"

export const professores: Professor[] = [
  {
    id: "ana-silva",
    nome: "Ana Silva",
    email: "ana.silva@academia.com",
    cor: "bg-purple-500",
    especialidades: ["Dança", "Zumba"],
    ativo: true,
  },
  {
    id: "carlos-mendes",
    nome: "Carlos Mendes",
    email: "carlos.mendes@academia.com",
    cor: "bg-orange-500",
    especialidades: ["Muay Thai", "Boxe"],
    ativo: true,
  },
  {
    id: "julia-santos",
    nome: "Julia Santos",
    email: "julia.santos@academia.com",
    cor: "bg-blue-500",
    especialidades: ["Ballet", "Jazz"],
    ativo: true,
  },
  {
    id: "pedro-costa",
    nome: "Pedro Costa",
    email: "pedro.costa@academia.com",
    cor: "bg-green-500",
    especialidades: ["Musculação", "Funcional"],
    ativo: true,
  },
  {
    id: "marina-oliveira",
    nome: "Marina Oliveira",
    email: "marina.oliveira@academia.com",
    cor: "bg-pink-500",
    especialidades: ["Dança Contemporânea", "Aula Particular"],
    ativo: true,
  },
  {
    id: "roberto-lima",
    nome: "Roberto Lima",
    email: "roberto.lima@academia.com",
    cor: "bg-indigo-500",
    especialidades: ["Jiu-Jitsu", "MMA"],
    ativo: true,
  },
]

export const tiposAula: TipoAula[] = [
  {
    id: "musculacao",
    nome: "Musculação",
    icone: "Dumbbell",
    cor: "bg-green-500",
    descricao: "Aulas de musculação para hipertrofia e força",
  },
  {
    id: "funcional",
    nome: "Funcional",
    icone: "Activity",
    cor: "bg-blue-500",
    descricao: "Treino funcional para condicionamento físico",
  },
  {
    id: "zumba",
    nome: "Zumba",
    icone: "Music",
    cor: "bg-purple-500",
    descricao: "Aulas de dança fitness com ritmos latinos",
  },
  {
    id: "ballet",
    nome: "Ballet",
    icone: "Heart",
    cor: "bg-pink-500",
    descricao: "Aulas de ballet clássico e contemporâneo",
  },
  {
    id: "muay-thai",
    nome: "Muay Thai",
    icone: "Circle",
    cor: "bg-orange-500",
    descricao: "Arte marcial tailandesa",
  },
  {
    id: "jiu-jitsu",
    nome: "Jiu-Jitsu",
    icone: "Shield",
    cor: "bg-indigo-500",
    descricao: "Arte marcial brasileira de luta no chão",
  },
  {
    id: "jazz",
    nome: "Jazz",
    icone: "Star",
    cor: "bg-yellow-500",
    descricao: "Dança jazz moderna",
  },
  {
    id: "boxe",
    nome: "Boxe",
    icone: "Square",
    cor: "bg-red-500",
    descricao: "Boxe inglês",
  },
  {
    id: "aula-particular",
    nome: "Aula Particular",
    icone: "User",
    cor: "bg-gray-500",
    descricao: "Aulas individuais personalizadas",
  },
]

export const alunos: Aluno[] = [
  {
    id: "1",
    nome: "Maria Silva",
    email: "maria.silva@email.com",
    telefone: "(11) 99999-9999",
    dataNascimento: new Date("1990-05-15"),
    plano: "Mensal",
    ativo: true,
    status: "ativo",
    aulasRealizadas: 15,
    treinosAtivos: 2,
    dataVencimento: new Date("2024-02-15"),
  },
  {
    id: "2",
    nome: "João Santos",
    email: "joao.santos@email.com",
    telefone: "(11) 88888-8888",
    dataNascimento: new Date("1985-08-22"),
    plano: "Trimestral",
    ativo: true,
    status: "ativo",
    aulasRealizadas: 28,
    treinosAtivos: 1,
    dataVencimento: new Date("2024-04-22"),
  },
  {
    id: "3",
    nome: "Ana Costa",
    email: "ana.costa@email.com",
    telefone: "(11) 77777-7777",
    dataNascimento: new Date("1995-03-10"),
    plano: "Semestral",
    ativo: true,
    status: "ativo",
    aulasRealizadas: 42,
    treinosAtivos: 3,
    dataVencimento: new Date("2024-07-10"),
  },
]

// Aulas de exemplo para a semana atual (dança, luta e musculação)
export const aulas: Aula[] = [
  // Segunda-feira
  {
    id: "1",
    tipoAulaId: "musculacao",
    professorId: "ana-silva",
    dataHora: new Date("2024-01-15T07:00:00"),
    quantidadeAlunos: 8,
    valorAula: 50.00,
    status: "agendada",
  },
  {
    id: "2",
    tipoAulaId: "zumba",
    professorId: "marina-oliveira",
    dataHora: new Date("2024-01-15T09:00:00"),
    quantidadeAlunos: 1,
    valorAula: 80.00,
    status: "agendada",
  },
  {
    id: "3",
    tipoAulaId: "musculacao",
    professorId: "carlos-mendes",
    dataHora: new Date("2024-01-15T18:00:00"),
    quantidadeAlunos: 11,
    valorAula: 50.00,
    status: "agendada",
  },
  
  // Terça-feira
  {
    id: "4",
    tipoAulaId: "muay-thai",
    professorId: "carlos-mendes",
    dataHora: new Date("2024-01-16T08:00:00"),
    quantidadeAlunos: 10,
    valorAula: 45.00,
    status: "agendada",
  },
  {
    id: "5",
    tipoAulaId: "jazz",
    professorId: "julia-santos",
    dataHora: new Date("2024-01-16T10:00:00"),
    quantidadeAlunos: 12,
    valorAula: 40.00,
    status: "agendada",
  },
  {
    id: "6",
    tipoAulaId: "zumba",
    professorId: "ana-silva",
    dataHora: new Date("2024-01-16T18:00:00"),
    quantidadeAlunos: 16,
    valorAula: 40.00,
    status: "agendada",
  },
  
  // Quarta-feira
  {
    id: "7",
    tipoAulaId: "funcional",
    professorId: "julia-santos",
    dataHora: new Date("2024-01-17T07:00:00"),
    quantidadeAlunos: 12,
    valorAula: 45.00,
    status: "agendada",
  },
  {
    id: "8",
    tipoAulaId: "funcional",
    professorId: "roberto-lima",
    dataHora: new Date("2024-01-17T09:00:00"),
    quantidadeAlunos: 14,
    valorAula: 45.00,
    status: "agendada",
  },
  {
    id: "9",
    tipoAulaId: "musculacao",
    professorId: "roberto-lima",
    dataHora: new Date("2024-01-17T18:00:00"),
    quantidadeAlunos: 7,
    valorAula: 50.00,
    status: "agendada",
  },
  
  // Quinta-feira
  {
    id: "10",
    tipoAulaId: "muay-thai",
    professorId: "carlos-mendes",
    dataHora: new Date("2024-01-18T08:00:00"),
    quantidadeAlunos: 8,
    valorAula: 45.00,
    status: "agendada",
  },
  {
    id: "11",
    tipoAulaId: "jiu-jitsu",
    professorId: "pedro-costa",
    dataHora: new Date("2024-01-18T10:00:00"),
    quantidadeAlunos: 18,
    valorAula: 55.00,
    status: "agendada",
  },
  
  // Sexta-feira
  {
    id: "12",
    tipoAulaId: "musculacao",
    professorId: "ana-silva",
    dataHora: new Date("2024-01-19T07:00:00"),
    quantidadeAlunos: 6,
    valorAula: 50.00,
    status: "agendada",
  },
  {
    id: "13",
    tipoAulaId: "ballet",
    professorId: "marina-oliveira",
    dataHora: new Date("2024-01-19T09:00:00"),
    quantidadeAlunos: 9,
    valorAula: 45.00,
    status: "agendada",
  },
  {
    id: "14",
    tipoAulaId: "boxe",
    professorId: "julia-santos",
    dataHora: new Date("2024-01-19T18:00:00"),
    quantidadeAlunos: 5,
    valorAula: 50.00,
    status: "agendada",
  },
  
  // Sábado
  {
    id: "15",
    tipoAulaId: "jiu-jitsu",
    professorId: "pedro-costa",
    dataHora: new Date("2024-01-20T08:00:00"),
    quantidadeAlunos: 15,
    valorAula: 55.00,
    status: "agendada",
  },
]

export const treinos: Treino[] = [
  {
    id: "1",
    alunoId: "1",
    professorId: "ana-silva",
    nome: "Treino A - Musculação",
    descricao: "Treino focado em hipertrofia e força",
    exercicios: [
      {
        id: "1",
        nome: "Supino Reto - 4x12",
        series: 4,
        repeticoes: 12,
        descanso: 60,
      },
      {
        id: "2",
        nome: "Agachamento - 4x10",
        series: 4,
        repeticoes: 10,
        descanso: 90,
      },
      {
        id: "3",
        nome: "Remada Curvada - 3x12",
        series: 3,
        repeticoes: 12,
        descanso: 60,
      },
    ],
    status: "ativo",
    dataCriacao: new Date("2024-01-01"),
    dataAtualizacao: new Date("2024-01-10"),
  },
  {
    id: "2",
    alunoId: "2",
    professorId: "carlos-mendes",
    nome: "Treino B - Muay Thai",
    descricao: "Treino intensivo para competição",
    exercicios: [
      {
        id: "4",
        nome: "Aquecimento - 10 min",
        series: 1,
        repeticoes: 1,
        descanso: 0,
      },
      {
        id: "5",
        nome: "Soco direto - 3x2min",
        series: 3,
        repeticoes: 1,
        descanso: 30,
      },
      {
        id: "6",
        nome: "Chute frontal - 3x2min",
        series: 3,
        repeticoes: 1,
        descanso: 45,
      },
    ],
    status: "ativo",
    dataCriacao: new Date("2024-01-05"),
    dataAtualizacao: new Date("2024-01-12"),
  },
]
